"""add task6 feedback snapshots

Revision ID: 0316b1a7de8e
Revises: b1d0d81b0b64
Create Date: 2026-08-27 22:49:45.865841

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0316b1a7de8e'
down_revision = 'b1d0d81b0b64'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('feedback', schema=None) as batch_op:
        batch_op.add_column(sa.Column('client_session_id', sa.String(length=64), server_default='legacy', nullable=False))
        batch_op.add_column(sa.Column('primary_policy_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('answer_snapshot', sa.JSON(), server_default=sa.text("'{}'"), nullable=False))
        batch_op.create_index(batch_op.f('ix_feedback_client_session_id'), ['client_session_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_feedback_primary_policy_id'), ['primary_policy_id'], unique=False)
        batch_op.create_foreign_key('fk_feedback_primary_policy', 'policies', ['primary_policy_id'], ['id'], ondelete='SET NULL')

    with op.batch_alter_table('regression_cases', schema=None) as batch_op:
        batch_op.create_unique_constraint('uq_regression_feedback', ['feedback_id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('regression_cases', schema=None) as batch_op:
        batch_op.drop_constraint('uq_regression_feedback', type_='unique')

    with op.batch_alter_table('feedback', schema=None) as batch_op:
        batch_op.drop_constraint('fk_feedback_primary_policy', type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_feedback_primary_policy_id'))
        batch_op.drop_index(batch_op.f('ix_feedback_client_session_id'))
        batch_op.drop_column('answer_snapshot')
        batch_op.drop_column('primary_policy_id')
        batch_op.drop_column('client_session_id')

    # ### end Alembic commands ###
