"""task2 knowledge base index state

Revision ID: f1098ad60503
Revises: a6996e6553d9
Create Date: 2026-08-27 17:01:19.555070

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f1098ad60503'
down_revision = 'a6996e6553d9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('index_snapshots', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_current', sa.Boolean(), nullable=False, server_default=sa.false()))
        batch_op.create_index(batch_op.f('ix_index_snapshots_is_current'), ['is_current'], unique=False)

    with op.batch_alter_table('policy_versions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('parse_error', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('policy_versions', schema=None) as batch_op:
        batch_op.drop_column('parse_error')

    with op.batch_alter_table('index_snapshots', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_index_snapshots_is_current'))
        batch_op.drop_column('is_current')

    # ### end Alembic commands ###
