"""task3 trusted chat snapshots

Revision ID: 8523228205a4
Revises: f1098ad60503
Create Date: 2026-08-27 21:56:15.989189

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8523228205a4'
down_revision = 'f1098ad60503'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('answers', schema=None) as batch_op:
        batch_op.add_column(sa.Column('evidence_snapshot', sa.JSON(), nullable=False, server_default=sa.text("'[]'")))
        batch_op.add_column(sa.Column('evidence_coverage', sa.Float(), nullable=False, server_default=sa.text("0")))
        batch_op.add_column(sa.Column('degraded_reason', sa.String(length=255), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('answers', schema=None) as batch_op:
        batch_op.drop_column('degraded_reason')
        batch_op.drop_column('evidence_coverage')
        batch_op.drop_column('evidence_snapshot')

    # ### end Alembic commands ###
