"""initial schema

Revision ID: a6996e6553d9
Revises: 
Create Date: 2026-08-27 16:14:46.394259

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a6996e6553d9'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('admin_users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=80), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('last_login_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('admin_users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_admin_users_username'), ['username'], unique=True)

    op.create_table('conversations',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('client_session_id', sa.String(length=64), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=True),
    sa.Column('scenario_state', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('conversations', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_conversations_client_session_id'), ['client_session_id'], unique=False)

    op.create_table('index_snapshots',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('fingerprint', sa.String(length=64), nullable=False),
    sa.Column('embedding_model', sa.String(length=200), nullable=False),
    sa.Column('chunker_version', sa.String(length=64), nullable=False),
    sa.Column('clause_count', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=24), nullable=False),
    sa.Column('built_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('index_snapshots', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_index_snapshots_fingerprint'), ['fingerprint'], unique=True)
        batch_op.create_index(batch_op.f('ix_index_snapshots_status'), ['status'], unique=False)

    op.create_table('policies',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=64), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('category', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('policies', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_policies_category'), ['category'], unique=False)
        batch_op.create_index(batch_op.f('ix_policies_code'), ['code'], unique=True)

    op.create_table('answers',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('conversation_id', sa.String(length=36), nullable=False),
    sa.Column('question', sa.Text(), nullable=False),
    sa.Column('normalized_question', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=24), nullable=False),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('scenario', sa.JSON(), nullable=False),
    sa.Column('action_card', sa.JSON(), nullable=False),
    sa.Column('knowledge_fingerprint', sa.String(length=64), nullable=True),
    sa.Column('is_degraded', sa.Boolean(), nullable=False),
    sa.Column('model_name', sa.String(length=120), nullable=True),
    sa.Column('latency_ms', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['conversation_id'], ['conversations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('answers', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_answers_conversation_id'), ['conversation_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_answers_knowledge_fingerprint'), ['knowledge_fingerprint'], unique=False)
        batch_op.create_index(batch_op.f('ix_answers_status'), ['status'], unique=False)

    op.create_table('messages',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('conversation_id', sa.String(length=36), nullable=False),
    sa.Column('role', sa.String(length=16), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['conversation_id'], ['conversations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('messages', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_messages_conversation_id'), ['conversation_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_messages_role'), ['role'], unique=False)

    op.create_table('policy_versions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('policy_id', sa.Integer(), nullable=False),
    sa.Column('version', sa.String(length=40), nullable=False),
    sa.Column('effective_date', sa.Date(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('file_name', sa.String(length=255), nullable=False),
    sa.Column('file_path', sa.String(length=500), nullable=False),
    sa.Column('mime_type', sa.String(length=120), nullable=False),
    sa.Column('size_bytes', sa.Integer(), nullable=False),
    sa.Column('file_sha256', sa.String(length=64), nullable=False),
    sa.Column('parsed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['policy_id'], ['policies.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('policy_id', 'version', name='uq_policy_version')
    )
    with op.batch_alter_table('policy_versions', schema=None) as batch_op:
        batch_op.create_index('ix_policy_active_version', ['policy_id', 'status'], unique=False)
        batch_op.create_index(batch_op.f('ix_policy_versions_file_sha256'), ['file_sha256'], unique=False)
        batch_op.create_index(batch_op.f('ix_policy_versions_policy_id'), ['policy_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_policy_versions_status'), ['status'], unique=False)

    op.create_table('query_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('conversation_id', sa.String(length=36), nullable=True),
    sa.Column('policy_id', sa.Integer(), nullable=True),
    sa.Column('question', sa.Text(), nullable=False),
    sa.Column('result_status', sa.String(length=24), nullable=False),
    sa.Column('top_score', sa.Float(), nullable=True),
    sa.Column('hit_count', sa.Integer(), nullable=False),
    sa.Column('retrieval_latency_ms', sa.Integer(), nullable=True),
    sa.Column('total_latency_ms', sa.Integer(), nullable=True),
    sa.Column('model_name', sa.String(length=120), nullable=True),
    sa.Column('is_degraded', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['conversation_id'], ['conversations.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['policy_id'], ['policies.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('query_logs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_query_logs_conversation_id'), ['conversation_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_query_logs_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_query_logs_is_degraded'), ['is_degraded'], unique=False)
        batch_op.create_index(batch_op.f('ix_query_logs_policy_id'), ['policy_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_query_logs_result_status'), ['result_status'], unique=False)
        batch_op.create_index('ix_query_status_created', ['result_status', 'created_at'], unique=False)

    op.create_table('claims',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('answer_id', sa.String(length=36), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('evidence_validated', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['answer_id'], ['answers.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('answer_id', 'position', name='uq_claim_position')
    )
    with op.batch_alter_table('claims', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_claims_answer_id'), ['answer_id'], unique=False)

    op.create_table('clauses',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('policy_version_id', sa.Integer(), nullable=False),
    sa.Column('stable_anchor', sa.String(length=96), nullable=False),
    sa.Column('section_path', sa.String(length=500), nullable=False),
    sa.Column('clause_number', sa.String(length=80), nullable=True),
    sa.Column('page_number', sa.Integer(), nullable=True),
    sa.Column('paragraph_index', sa.Integer(), nullable=True),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('text_sha256', sa.String(length=64), nullable=False),
    sa.Column('embedding', sa.LargeBinary(), nullable=True),
    sa.Column('token_count', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['policy_version_id'], ['policy_versions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('clauses', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_clauses_clause_number'), ['clause_number'], unique=False)
        batch_op.create_index(batch_op.f('ix_clauses_policy_version_id'), ['policy_version_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_clauses_stable_anchor'), ['stable_anchor'], unique=True)
        batch_op.create_index(batch_op.f('ix_clauses_text_sha256'), ['text_sha256'], unique=False)

    op.create_table('feedback',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('conversation_id', sa.String(length=36), nullable=True),
    sa.Column('answer_id', sa.String(length=36), nullable=True),
    sa.Column('submitter_name', sa.String(length=80), nullable=True),
    sa.Column('is_anonymous', sa.Boolean(), nullable=False),
    sa.Column('feedback_type', sa.String(length=40), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('auto_category', sa.String(length=40), nullable=True),
    sa.Column('status', sa.String(length=24), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['answer_id'], ['answers.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['conversation_id'], ['conversations.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('feedback', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_feedback_answer_id'), ['answer_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_feedback_auto_category'), ['auto_category'], unique=False)
        batch_op.create_index(batch_op.f('ix_feedback_conversation_id'), ['conversation_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_feedback_feedback_type'), ['feedback_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_feedback_status'), ['status'], unique=False)
        batch_op.create_index('ix_feedback_status_created', ['status', 'created_at'], unique=False)

    op.create_table('claim_evidences',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('claim_id', sa.Integer(), nullable=False),
    sa.Column('clause_id', sa.Integer(), nullable=False),
    sa.Column('rank', sa.Integer(), nullable=False),
    sa.Column('quote_snapshot', sa.Text(), nullable=False),
    sa.Column('policy_version_snapshot', sa.String(length=40), nullable=False),
    sa.ForeignKeyConstraint(['claim_id'], ['claims.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['clause_id'], ['clauses.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('claim_id', 'clause_id', name='uq_claim_clause')
    )
    with op.batch_alter_table('claim_evidences', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_claim_evidences_claim_id'), ['claim_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_claim_evidences_clause_id'), ['clause_id'], unique=False)

    op.create_table('feedback_events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('feedback_id', sa.String(length=36), nullable=False),
    sa.Column('actor_type', sa.String(length=24), nullable=False),
    sa.Column('action', sa.String(length=40), nullable=False),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('event_data', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['feedback_id'], ['feedback.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('feedback_events', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_feedback_events_feedback_id'), ['feedback_id'], unique=False)

    op.create_table('regression_cases',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('feedback_id', sa.String(length=36), nullable=True),
    sa.Column('question', sa.Text(), nullable=False),
    sa.Column('scenario', sa.JSON(), nullable=False),
    sa.Column('expected_evidence', sa.JSON(), nullable=False),
    sa.Column('status', sa.String(length=24), nullable=False),
    sa.Column('last_run_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_result', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['feedback_id'], ['feedback.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('regression_cases', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_regression_cases_feedback_id'), ['feedback_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_regression_cases_status'), ['status'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('regression_cases', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_regression_cases_status'))
        batch_op.drop_index(batch_op.f('ix_regression_cases_feedback_id'))

    op.drop_table('regression_cases')
    with op.batch_alter_table('feedback_events', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_feedback_events_feedback_id'))

    op.drop_table('feedback_events')
    with op.batch_alter_table('claim_evidences', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_claim_evidences_clause_id'))
        batch_op.drop_index(batch_op.f('ix_claim_evidences_claim_id'))

    op.drop_table('claim_evidences')
    with op.batch_alter_table('feedback', schema=None) as batch_op:
        batch_op.drop_index('ix_feedback_status_created')
        batch_op.drop_index(batch_op.f('ix_feedback_status'))
        batch_op.drop_index(batch_op.f('ix_feedback_feedback_type'))
        batch_op.drop_index(batch_op.f('ix_feedback_conversation_id'))
        batch_op.drop_index(batch_op.f('ix_feedback_auto_category'))
        batch_op.drop_index(batch_op.f('ix_feedback_answer_id'))

    op.drop_table('feedback')
    with op.batch_alter_table('clauses', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_clauses_text_sha256'))
        batch_op.drop_index(batch_op.f('ix_clauses_stable_anchor'))
        batch_op.drop_index(batch_op.f('ix_clauses_policy_version_id'))
        batch_op.drop_index(batch_op.f('ix_clauses_clause_number'))

    op.drop_table('clauses')
    with op.batch_alter_table('claims', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_claims_answer_id'))

    op.drop_table('claims')
    with op.batch_alter_table('query_logs', schema=None) as batch_op:
        batch_op.drop_index('ix_query_status_created')
        batch_op.drop_index(batch_op.f('ix_query_logs_result_status'))
        batch_op.drop_index(batch_op.f('ix_query_logs_policy_id'))
        batch_op.drop_index(batch_op.f('ix_query_logs_is_degraded'))
        batch_op.drop_index(batch_op.f('ix_query_logs_created_at'))
        batch_op.drop_index(batch_op.f('ix_query_logs_conversation_id'))

    op.drop_table('query_logs')
    with op.batch_alter_table('policy_versions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_policy_versions_status'))
        batch_op.drop_index(batch_op.f('ix_policy_versions_policy_id'))
        batch_op.drop_index(batch_op.f('ix_policy_versions_file_sha256'))
        batch_op.drop_index('ix_policy_active_version')

    op.drop_table('policy_versions')
    with op.batch_alter_table('messages', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_messages_role'))
        batch_op.drop_index(batch_op.f('ix_messages_conversation_id'))

    op.drop_table('messages')
    with op.batch_alter_table('answers', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_answers_status'))
        batch_op.drop_index(batch_op.f('ix_answers_knowledge_fingerprint'))
        batch_op.drop_index(batch_op.f('ix_answers_conversation_id'))

    op.drop_table('answers')
    with op.batch_alter_table('policies', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_policies_code'))
        batch_op.drop_index(batch_op.f('ix_policies_category'))

    op.drop_table('policies')
    with op.batch_alter_table('index_snapshots', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_index_snapshots_status'))
        batch_op.drop_index(batch_op.f('ix_index_snapshots_fingerprint'))

    op.drop_table('index_snapshots')
    with op.batch_alter_table('conversations', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_conversations_client_session_id'))

    op.drop_table('conversations')
    with op.batch_alter_table('admin_users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_admin_users_username'))

    op.drop_table('admin_users')
    # ### end Alembic commands ###
