"""add task5 answer workflow fields

Revision ID: b1d0d81b0b64
Revises: 8523228205a4
Create Date: 2026-08-27 22:31:45.755732

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b1d0d81b0b64'
down_revision = '8523228205a4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('answers', schema=None) as batch_op:
        batch_op.add_column(sa.Column('clarification', sa.JSON(), server_default=sa.text("'{}'"), nullable=False))
        batch_op.add_column(sa.Column('source_answer_id', sa.String(length=36), nullable=True))
        batch_op.add_column(sa.Column('generation_kind', sa.String(length=20), server_default='query', nullable=False))
        batch_op.create_index(batch_op.f('ix_answers_generation_kind'), ['generation_kind'], unique=False)
        batch_op.create_index(batch_op.f('ix_answers_source_answer_id'), ['source_answer_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('answers', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_answers_source_answer_id'))
        batch_op.drop_index(batch_op.f('ix_answers_generation_kind'))
        batch_op.drop_column('generation_kind')
        batch_op.drop_column('source_answer_id')
        batch_op.drop_column('clarification')

    # ### end Alembic commands ###
